version: '3.7'
services:
  spring-boot-example:
    build:
      context: .
    ports:
      target: 80
      published: 8080
      protocol: tcp
      mode: host
    container_name: byse-spring-boot-example
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip